#!/usr/bin/with-contenv bash

rm -rf /app/*
#mkdir -p /app/Jackett

#Get latest version of release
url="https://api.github.com/repos/abeloin/Jackett/releases"
tag=$(curl -sX GET "$url" | awk '/tag_name/{print $4;exit}' FS='[""]')
ARCH=`uname -m`

curl -o /tmp/jackett.tar.gz -L "https://github.com/abeloin/Jackett/releases/download/$tag/Jackett.Binaries.LinuxAMDx64.tar.gz"
tar -xzf /tmp/jackett.tar.gz -C /app/
#mv /tmp/Jackett/* /app/Jackett/

chmod +x /app/Jackett/*.sh
chmod +x /app/Jackett/jackett

echo "**** fix for host id mapping error ****"
chown -R root:root /app/Jackett

chown -R abc:abc \
	/app \
	/config \
	/downloads
